[phases.setup]
nixPkgs = ["python311", "libGL"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 300 --max-requests 1000 app:app"
