[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 300 app:app"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
